[package]
name = "lfu-cache"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
linked-vector = { git = "https://github.com/ttappr/linked-vector.git", branch = "v1.0.0-successor" }
